### ISSUE TITLE
Reading Evora / T6 ECU

### ISSUE THREAD

**Issue by Friss** [Alcantor/LotusECU-T4e#1]
I have 2 Evoras' one with a dev build "encryption flag false" that powers a 400 engine and a stock NA ECU with encryption flag true" 

Curious if this would be able to pull the data on the ECU and potentially modify it. 

I have a CarDAQ Plus 2 (http://drewtech.com/products/cardaqplus3.html is the plus 3 but same idea) and curious if it would work with your program. 

I have already used the cardaq with Lotus's 20/20 to read and write updates so it should be able to act as the passthrough.

**Comment by Alcantor** [comment]
Hi Friss,

You can maybe use my "CRP08 Editor" to edit the file downloaded by the Lotus's 20/20 Software.

By doing an update with the Lotus's 20/20, a CRP file is downloaded in background, have a look into:

"C:\ProgramData\SomitSolutionsLtd\LotusServiceDiagnostics\Content\ProgramFiles\EMS"

If you find the update file, you should be able to decrypt the file and extract the maps with my tools. Then to edit the maps a RomRaider Definition file would be ideally needed, but there are other possibilities... (I have made only a definition file for the T4e, it's a huge work).

After editing the file (maps) you could repack it and maybe flash it with the Lotus's 20/20....

My tools does not support any J2534 cables at this point (CarDAQ Plus 2). But if you want to contribute, I will gladly appreciate it!
